# See GitHub's documentation for more information on this file:
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
version: 2
updates:
  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      # Check for updates to Go modules every weekday
      interval: "daily"
    groups:
      # Group all terraform-plugin-(go|sdk|framework|testing) dependencies together
      "terraform-plugin":
        patterns:
          - "github.com/hashicorp/terraform-plugin-*"
  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      "github-actions":
        patterns:
          - "*" # Group all GitHub Actions dependencies together
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
